Fix: Remove invalid QueryBuildStage.Window reference
Hopping() was setting _stage = QueryBuildStage.Window, but Window is not
defined in QueryBuildStage enum. Following Tumbling() pattern, window
methods should not modify _stage.

This fixes the compilation error:
  QueryBuildStage.Window does not exist (KsqlQueryable.cs:124)